import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import consentRouter from "./consent";
import tracksRouter from "./tracks";
import assessmentsRouter from "./assessments";
import platformRouter from "./platform";
import dashboardRouter from "./dashboard";
import learningRouter from "./learning";
import labsRouter from "./labs";
import jobsRouter from "./jobs";
import profileRouter from "./profile";
import platformExtendedRouter from "./platform-extended";
import adminRouter from "./admin";
import adminMentorsRouter from "./admin-mentors";
import adminExtendedRouter from "./admin-extended";
import mentorRouter from "./mentor";
import tpoRouter from "./tpo";
import employerRouter from "./employer";
import aiRouter from "./ai";
import aiInterviewRouter from "./ai-interview";
import notificationsRouter from "./notifications";
import jobAgentRouter from "./job-agent";
import placementRouter from "./placement";
import campusRouter from "./campus";
import subscriptionRouter from "./subscription";
import analyticsRouter from "./analytics";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(consentRouter);
router.use(tracksRouter);
router.use(assessmentsRouter);
router.use(platformRouter);
router.use(dashboardRouter);
router.use(learningRouter);
router.use(labsRouter);
router.use(jobsRouter);
router.use(profileRouter);
router.use(notificationsRouter);
router.use(jobAgentRouter);
router.use(placementRouter);
router.use(campusRouter);
router.use(subscriptionRouter);
router.use(analyticsRouter);
router.use(platformExtendedRouter);
router.use(aiRouter);
router.use(aiInterviewRouter);
router.use(adminRouter);
router.use(adminMentorsRouter);
router.use(adminExtendedRouter);
router.use(mentorRouter);
router.use(tpoRouter);
router.use(employerRouter);

export default router;
