import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import consentRouter from "./consent";
import tracksRouter from "./tracks";
import assessmentsRouter from "./assessments";
import platformRouter from "./platform";
import dashboardRouter from "./dashboard";
import learningRouter from "./learning";
import labsRouter from "./labs";
import jobsRouter from "./jobs";
import profileRouter from "./profile";
import platformExtendedRouter from "./platform-extended";
import adminRouter from "./admin";
import adminMentorsRouter from "./admin-mentors";
import adminExtendedRouter from "./admin-extended";
import adminFtsRouter from "./admin-fts";
import adminCoursesRouter from "./admin-courses";
import adminLabsRouter from "./admin-labs";
import adminAssessmentsRouter from "./admin-assessments";
import adminCertificatesRouter from "./admin-certificates";
import adminJobPostingsRouter from "./admin-job-postings";
import adminAiRouter from "./admin-ai";
import adminSettingsRouter from "./admin-settings";
import adminTracksRouter from "./admin-tracks";
import adminDashboardRouter from "./admin-dashboard";
import mentorRouter from "./mentor";
import mentorQuestionBankRouter from "./mentor-question-bank";
import adminQuestionBankRouter from "./admin-question-bank";
import tpoRouter from "./tpo";
import employerRouter from "./employer";
import aiRouter from "./ai";
import aiInterviewRouter from "./ai-interview";
import mentorMockInterviewRouter from "./mentor-mock-interview";
import studentMockInterviewRouter from "./student-mock-interview";
import notificationsRouter from "./notifications";
import jobAgentRouter from "./job-agent";
import placementRouter from "./placement";
import campusRouter from "./campus";
import subscriptionRouter from "./subscription";
import analyticsRouter from "./analytics";
import labBuilderRouter from "./lab-builder";
import placementDrivesRouter from "./placement-drives";
import retentionRouter from "./retention";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(consentRouter);
router.use(tracksRouter);
router.use(assessmentsRouter);
router.use(platformRouter);
router.use(dashboardRouter);
router.use(learningRouter);
router.use(labsRouter);
router.use(jobsRouter);
router.use(profileRouter);
router.use(notificationsRouter);
router.use(jobAgentRouter);
router.use(placementRouter);
router.use(campusRouter);
router.use(subscriptionRouter);
router.use(analyticsRouter);
router.use(platformExtendedRouter);
router.use(aiRouter);
router.use(aiInterviewRouter);
router.use(mentorMockInterviewRouter);
router.use(studentMockInterviewRouter);
router.use(adminRouter);
router.use(adminMentorsRouter);
router.use(adminExtendedRouter);
router.use(adminFtsRouter);
router.use(adminCoursesRouter);
router.use(adminLabsRouter);
router.use(adminAssessmentsRouter);
router.use(adminCertificatesRouter);
router.use(adminJobPostingsRouter);
router.use(adminAiRouter);
router.use(adminSettingsRouter);
router.use(adminTracksRouter);
router.use(adminDashboardRouter);
router.use(mentorRouter);
router.use(mentorQuestionBankRouter);
router.use(adminQuestionBankRouter);
router.use(tpoRouter);
router.use(employerRouter);
router.use(labBuilderRouter);
router.use(placementDrivesRouter);
router.use("/admin/retention", retentionRouter);

export default router;
