kind = "web"
previewPath = "/"
title = "FUTRSEC"
version = "1.0.0"
id = "artifacts/futrsec"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18285

[services.development]
run = "pnpm --filter @workspace/futrsec run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/futrsec", "run", "build" ]
publicDir = "artifacts/futrsec/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18285"
BASE_PATH = "/"
