import {
  pgTable,
  serial,
  text,
  timestamp,
  integer,
  boolean,
  jsonb,
  pgEnum,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { careerTrackEnum } from "./users";
import { questionDifficultyEnum } from "./question-bank";

// ─────────────────────────────────────────────────────────────────────────────
// Enums
// ─────────────────────────────────────────────────────────────────────────────
export const mockInterviewTypeEnum = pgEnum("mock_interview_type", [
  "technical",
  "hr",
  "scenario",
  "practical",
  "viva",
  "mixed",
]);

export const mockInterviewTemplateStatusEnum = pgEnum(
  "mock_interview_template_status",
  ["draft", "published", "archived"]
);

export const mockInterviewAssignmentStatusEnum = pgEnum(
  "mock_interview_assignment_status",
  ["assigned", "in_progress", "completed", "missed"]
);

// How a mentor sources questions for a template.
export const mockInterviewSourceEnum = pgEnum("mock_interview_source", [
  "ai", // questions generated by AI at runtime
  "bank", // pinned questions from the mentor's question bank
  "custom", // mentor-authored free-form questions
]);

// ─────────────────────────────────────────────────────────────────────────────
// Mock Interview Templates — a reusable interview configuration authored by a
// mentor, then assigned to their students/batches. Distinct from a student's
// self-serve AI interview (which has no template).
// ─────────────────────────────────────────────────────────────────────────────
export const mockInterviewTemplatesTable = pgTable("mock_interview_templates", {
  id: serial("id").primaryKey(),
  createdBy: integer("created_by").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  careerTrack: careerTrackEnum("career_track").notNull(),
  interviewType: mockInterviewTypeEnum("interview_type")
    .notNull()
    .default("technical"),
  difficulty: questionDifficultyEnum("difficulty")
    .notNull()
    .default("intermediate"),
  status: mockInterviewTemplateStatusEnum("status").notNull().default("draft"),

  // Structure
  totalQuestions: integer("total_questions").notNull().default(10),
  durationMin: integer("duration_min").notNull().default(30),
  rounds: integer("rounds").notNull().default(1),
  passingScore: integer("passing_score").notNull().default(60),
  allowVoice: boolean("allow_voice").notNull().default(true),

  // Question sourcing
  questionSource: mockInterviewSourceEnum("question_source")
    .notNull()
    .default("ai"),
  questionBankIds: integer("question_bank_ids").array().notNull().default([]),
  // [{ index: number, question: string }] when questionSource = custom
  customQuestions: jsonb("custom_questions"),
  focusSkills: text("focus_skills").array().notNull().default([]),
  instructions: text("instructions"),

  // Scheduling
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
  deadline: timestamp("deadline", { withTimezone: true }),
  publishedAt: timestamp("published_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),

  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// ─────────────────────────────────────────────────────────────────────────────
// Assignments — one row per (template, student). `interviewId` links to the
// `ai_interviews` row once the student starts the assigned interview.
// ─────────────────────────────────────────────────────────────────────────────
export const mockInterviewAssignmentsTable = pgTable(
  "mock_interview_assignments",
  {
    id: serial("id").primaryKey(),
    templateId: integer("template_id").notNull(),
    studentId: integer("student_id").notNull(),
    batchId: integer("batch_id"),
    assignedBy: integer("assigned_by").notNull(),
    status: mockInterviewAssignmentStatusEnum("status")
      .notNull()
      .default("assigned"),
    // Set when the student begins — points at the ai_interviews attempt.
    interviewId: integer("interview_id"),
    dueAt: timestamp("due_at", { withTimezone: true }),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    score: integer("score"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    uniqTemplateStudent: uniqueIndex("uniq_mock_interview_template_student").on(
      t.templateId,
      t.studentId
    ),
  })
);

export type MockInterviewTemplate =
  typeof mockInterviewTemplatesTable.$inferSelect;
export type MockInterviewAssignment =
  typeof mockInterviewAssignmentsTable.$inferSelect;
